version: "3"
services:
  envoy:
    image: envoyproxy/envoy:dev-3f0b409ec062baec62d650d86333250d0b893df7
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "3001:3001"
